# Generated by Django 5.1.3 on 2025-02-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='message',
            new_name='bot_response',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='response',
            new_name='user_input',
        ),
        migrations.AlterField(
            model_name='chat',
            name='sentiment',
            field=models.CharField(max_length=10),
        ),
    ]
