from django.shortcuts import render, redirect
from django.http import JsonResponse
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from .models import ChatLog
from docx import Document
import os
import random
from django.utils import timezone
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
# Initialize the sentiment analyzer
sia = SentimentIntensityAnalyzer()

# Define responses based on detected emotions
emotion_responses = {
    'anger': ["I understand you're feeling angry. What happened?",
    "I'm sorry you're feeling upset. Let’s try to work through it.",
    "It sounds like you're really frustrated. How can I help?",
    "I can see you're angry. Want to talk about what's bothering you?",
    "Anger is a tough emotion. Let me know how I can support you.",
    "It’s okay to feel angry. What’s causing this frustration?",
    "I hear you. What can I do to help you calm down?",
    "I'm here if you want to talk through your anger.",
    "It’s okay to feel mad, but let’s see if we can work through it together.",
    "I understand you're upset, and I’m here to listen if you need it.",
    "Anger can be overwhelming. Want to talk about what’s going on?",
    "I can sense your anger. Let me know what triggered it.",
    "You’re not alone in this feeling. What’s making you upset?",
    "Feeling angry is tough. How can I make this better for you?",
    "I can hear the frustration in your words. Let’s talk it out.",
    "You seem upset. Want to share what’s causing you to feel this way?",
    "I’m sorry you’re angry. What can we do to fix things?",
    "Take a deep breath. I’m here to listen if you need to vent.",
    "It’s understandable to be mad right now. Let me know if you want to talk.",
    "I’m really sorry you’re feeling this way. Want to share your thoughts?",
    "I can sense your anger. What happened, if you don’t mind sharing?",
    "It's okay to feel angry, but let's try to figure out a solution together.",
    "I’m here to listen. Let me know what’s bothering you.",
    "Anger can cloud things. Let me help you find clarity.",
    "You're upset, and I want to help. What's causing this frustration?",
    "I get it, you’re feeling mad. Do you want to vent or talk through it?",
    "It’s okay to feel this way. Let me know what’s on your mind.",
    "I hear your anger. Let’s take a step back and see how we can resolve this.",
    "Let me help you make sense of things. What’s making you angry?",
    "It’s perfectly fine to be angry, but talking about it might help. Shall we?",
    "I’m sorry things are making you feel this way. Let’s figure it out.",
    "I understand you’re frustrated. I’m here if you need to talk.",
    "Take your time, I’m here to listen to whatever’s bothering you.",
    "Sometimes anger comes from feeling misunderstood. Let me hear you out.",
    "I’m really sorry you’re feeling angry. Let's work through it together.",
    "Anger can feel like a heavy weight. Let me help carry some of it.",
    "I see you’re frustrated. What can we do to resolve it?",
    "I understand that things are tough right now. What can I do to make it better?",
    "I’m sorry you're upset. Do you want to tell me what triggered your anger?",
    "Anger is hard to deal with alone. Let’s talk it through.",
    "You deserve to be heard. What’s going on that’s making you angry?",
    "It’s okay to feel mad. Let’s see if we can work through this together.",
    "I’m sorry you're feeling this way. Let’s figure out how to resolve it.",
    "I understand that you're upset. How can we work towards a solution?",
    "Anger is an emotion we all feel. Let me know how I can help ease it.",
    "Your frustration is understandable. Let’s find a way to deal with it.",
    "It sounds like you're overwhelmed. Can I help in any way?",
    "It’s okay to feel angry sometimes. What can I do to make things better?",
    "I hear your frustration. Would it help if I just listened?",
    "You seem really upset. What can we do to ease your anger?",
    "I’m here to listen and help. What’s making you so mad?",
    "Let’s try to understand what’s triggering your anger. I’m here for you.",
    "It’s tough when things don’t go right. Let’s talk it through.",
    "I get why you're mad. How can I help you resolve this?",
    "I understand you’re upset, but I’m here if you need to vent.",
    "I can see you're angry. Want to share what's causing it?",
    "Your anger is valid. Let’s focus on fixing what went wrong.",
    "You don’t have to carry that anger alone. I’m here to help.",
    "I’m sorry you’re going through this. How can I assist in making it better?",
    "Anger can feel intense. Let’s work together to calm things down.",
    "I’m really sorry you're upset. Let me know what’s causing your frustration.",
    "Sometimes talking about it helps. What’s making you feel this way?",
    "I understand you're angry, but let’s focus on what can be done.",
    "I hear your frustration, and I'm here to help you through it.",
    "It’s okay to be mad. What happened?",
    "Your anger is valid, but I’m here to support you in working through it.",
    "I can sense your anger. Want to talk about how we can move past it?",
    "I get it, you’re upset. What’s the best way I can help?",
    "I’m really sorry you’re feeling angry. Let me know how I can make it better.",
    "Let’s find a way to calm things down. What’s causing the anger?",
    "It’s okay to express your anger. What happened that’s making you feel this way?",
    "I can feel your frustration. What can I do to make it easier?",
    "Anger is a natural response, but let’s work on a solution together.",
    "I’m sorry you’re feeling angry. Want to tell me what happened?",
    "It seems like something upset you. Let’s talk about it.",
    "I can tell this is really bothering you. How can I assist?",
    "I hear you, and I’m here to listen. What’s making you feel this way?",
    "Sometimes anger comes from unmet expectations. Let’s talk about it.",
    "I understand your anger, and I’m here to help you with it.",
    "You’re not alone in this. Let me know how I can support you.",
    "I know you’re upset. Let’s work together to figure out a way forward.",
    "I’m sorry you’re feeling angry. What happened?",
    "I can feel the frustration in your words. Let me know how I can help.",
    "I hear you. What happened that’s making you angry?",
    "I’m here for you. What’s causing all this anger?",
    "I understand you're upset. Let’s try to make things right.",
    "Anger can cloud judgment. Let’s see if we can find clarity.",
    "I know this is difficult. Want to share what triggered your anger?",
    "I hear you. It’s okay to be angry. How can I assist?",
    "I know you’re frustrated. What can we do to help you feel better?",
    "I understand you're feeling this way. Let’s talk about what’s going on.",
    "Your feelings are valid. Let’s figure this out together.",
    "I can hear the frustration in your voice. How can I help?",
    "I’m sorry you're feeling this way. What can we do about it?",
    "I can sense the anger in your words. Let’s talk through it.",
    "Anger can overwhelm us. Let’s find a way to calm down.",
    "I hear you. Let’s work together to move past this frustration.",
    "It’s okay to express your anger. Let’s see how we can work through it.",
    "I’m really sorry you’re upset. Let’s talk it through together.",
    "Your anger is understandable. Let’s figure out how to move forward."],
    
    'fear': [
    "I can sense you're feeling fearful. What’s on your mind?",
    "It's okay to feel scared sometimes. What’s making you feel this way?",
    "I understand fear can be overwhelming. Want to talk about it?",
    "Fear is natural. Let me know how I can help you through it.",
    "It’s okay to feel afraid. What’s causing this fear?",
    "I’m here for you. Want to share what's making you anxious?",
    "Fear can be tough, but you’re not alone. What’s bothering you?",
    "You don't have to face fear by yourself. I’m here to listen.",
    "I understand you're scared. Let’s work through it together.",
    "Fear is powerful, but we can get through it. What’s scaring you?",
    "Take a deep breath. I’m here for you if you want to talk about it.",
    "It’s okay to be afraid. Let’s figure out what’s causing these feelings.",
    "I can hear the fear in your words. Want to share what’s on your mind?",
    "You don’t have to carry this fear alone. Let’s talk through it.",
    "Feeling afraid is a natural part of life. How can I help you manage it?",
    "I can understand why you're scared. Do you want to talk about it?",
    "Fear can make things seem worse than they are. Let’s put things in perspective.",
    "I’m really sorry you’re feeling afraid. Let’s figure out what’s causing it.",
    "It's okay to have fears. How can I help you feel safer?",
    "I hear your fear. Want to talk through what’s causing it?",
    "You’re not alone in this fear. Let me help you work through it.",
    "Fear is something we all face. I’m here to listen if you want to talk.",
    "I know it can be tough. What’s making you feel fearful right now?",
    "It’s okay to feel fear. What’s on your mind?",
    "I can feel that you're anxious. Let me know how I can assist you.",
    "You don't have to be afraid alone. Let me help you through it.",
    "I can sense you're afraid. Want to share what triggered this fear?",
    "Fear can cloud your judgment. Let’s take a moment and think things through.",
    "You don’t have to face this fear by yourself. I’m here for you.",
    "I understand that fear is powerful. Let’s talk about what’s causing it.",
    "It’s okay to be afraid. How can I help you calm down?",
    "I hear that you're scared. Do you want to tell me what's going on?",
    "I understand that you're anxious. Let’s talk through this fear together.",
    "Fear can be overwhelming, but it’s something we can work through.",
    "I hear your fear. What can I do to make you feel safer?",
    "You don’t have to carry your fear alone. Let’s talk it out.",
    "I understand that fear can be consuming. Want to talk more about it?",
    "It’s okay to feel afraid. How can I help you feel more at ease?",
    "Fear can be paralyzing. Let’s find a way to overcome it.",
    "I’m really sorry you're feeling fearful. Want to share more about it?",
    "I know fear can feel like a heavy burden. Let’s lighten it together.",
    "It’s okay to feel anxious. Let me help you through it.",
    "I understand that you’re feeling fear. What’s making you feel this way?",
    "You’re not alone in this fear. Let me know how I can support you.",
    "I hear the anxiety in your voice. What can I do to help you?",
    "Fear is a very real emotion. Let’s talk about what’s going on.",
    "I understand that you’re scared. Let me help you find a way forward.",
    "I can sense your fear. Want to talk about what triggered it?",
    "It’s okay to be afraid. Let’s talk through what’s causing these feelings.",
    "Fear is natural, but we can work through it together. What’s scaring you?",
    "I can hear the fear in your words. Want to talk more about it?",
    "It’s okay to feel anxious. Let’s break down what’s making you afraid.",
    "Fear is something we all face. You’re not alone in this.",
    "I’m really sorry you’re feeling scared. Want to share what’s going on?",
    "It’s okay to have fear. Let’s work together to calm those feelings.",
    "Fear can be overwhelming, but we can work through it together.",
    "I hear that you’re afraid. How can I help you manage this fear?",
    "I understand fear can be tough. What’s making you feel this way?",
    "I know you're scared right now. Let’s talk about it together.",
    "It’s okay to feel fear. What can I do to help ease it?",
    "I hear your fear. Want to tell me what’s triggering it?",
    "You don’t have to face fear alone. I’m here for you.",
    "It’s okay to feel anxious. Let’s figure out how to deal with it together.",
    "I understand that you’re fearful. What’s causing this anxiety?",
    "I can sense your fear. Let’s talk through what’s making you anxious.",
    "Fear is a natural part of life. Let’s find a way to manage it.",
    "I know you’re feeling afraid. Want to talk more about what’s going on?",
    "I hear the anxiety in your voice. What’s on your mind?",
    "I understand that you’re scared. Let’s talk about how to handle it.",
    "I know fear can be paralyzing. Let’s talk through it together.",
    "It’s okay to feel afraid. Let me help you through it.",
    "I understand fear can be hard to face. Want to talk more about it?",
    "I hear your fear, and I’m here to listen if you need to share.",
    "It’s okay to feel anxious. Let’s talk about what’s making you feel this way.",
    "Fear can make things seem worse. Let me help you see things clearer.",
    "I hear the fear in your words. Want to talk through it?",
    "It’s okay to be afraid, but we can work through this together.",
    "I understand you're scared. What can we do to make it better?",
    "I can sense your fear. Let’s break it down together.",
    "Fear is tough, but we can manage it together. What’s going on?",
    "I understand that fear can be overwhelming. Let’s talk it through.",
    "I hear your fear. Want to share what’s causing it?",
    "I know that you're scared. Let me help you face it.",
    "It’s okay to feel anxious. How can I help you through this fear?",
    "I understand fear can feel paralyzing. Let’s work through it together.",
    "Fear can be hard to handle, but I’m here for you.",
    "I can sense your fear. Want to share what's on your mind?",
    "Fear is a normal feeling. Let’s talk about what’s making you scared.",
    "It’s okay to be afraid. Let’s see how we can work through it.",
    "I hear that you’re anxious. Let’s break down what's causing it.",
    "I understand you're feeling fearful. What can I do to help?",
    "I know fear can feel like a weight. Let’s figure out how to ease it.",
    "I’m here to help you face your fear. Want to talk through it?",
    "I can sense you're scared. Let’s talk more about what’s going on.",
    "Fear can be unsettling. Let’s work through it together.",
    "It’s okay to feel fearful. Want to share what's causing it?",
    "I hear the anxiety in your voice. Let’s talk it through together.",
    "I understand that fear can be overwhelming. Want to discuss it?",
    "I can sense you're afraid. Let’s break it down and see how to handle it.",
    "It’s okay to feel fear. Let’s find a way to move through it.",
    "I understand you’re scared. What can we do to help you feel better?",
    "Fear can be tough, but I’m here to help you work through it."
],

    'joy' : [
    "I'm so happy to hear that you're feeling joyful! Keep that positive energy going!",
    "That’s amazing! I'm glad you're feeling joyful. What's making you so happy?",
    "It's great to hear you're in a joyful mood! What’s the good news?",
    "I'm so happy for you! Keep embracing that joy!",
    "It sounds like you're really enjoying yourself! Keep that happiness alive.",
    "I’m thrilled to hear you're feeling joyful! What’s bringing you so much joy?",
    "Joy is such a wonderful feeling. I'm so glad you're experiencing it!",
    "I’m so glad you’re feeling happy! Let that joy fill your heart.",
    "That’s wonderful! Hold on to that joy and keep smiling.",
    "It sounds like you're on cloud nine! Enjoy every moment of that happiness.",
    "Yay! I’m so happy you're feeling joyful. What’s been making you so happy?",
    "I’m glad to hear you're feeling this way! Keep the good vibes going.",
    "Joy is contagious! I'm so happy you're radiating it.",
    "Your happiness is so uplifting! What’s making your day so wonderful?",
    "I love hearing that you're filled with joy! Keep celebrating that positivity.",
    "It’s amazing to see you so happy! Let that joy carry you throughout the day.",
    "That’s awesome! Enjoy every moment of your joy!",
    "I’m really happy you're feeling joyful. What’s the best part of your day?",
    "I’m glad you’re feeling this way! It’s great to see such positivity.",
    "It’s so great to hear you're in such a good mood! Keep it up!",
    "It sounds like everything is going great for you! Stay joyful!",
    "I'm so happy to hear you're feeling positive! What’s making you smile today?",
    "I’m loving this joyful energy you have! Keep it going.",
    "That’s fantastic! I’m so happy to hear you're full of joy!",
    "You deserve all this happiness! Keep smiling and enjoy your joy.",
    "I can feel your happiness from here! What’s been the highlight of your day?",
    "It’s wonderful that you’re feeling so joyful! Embrace it fully.",
    "Such great news! Stay happy and keep spreading that joy.",
    "Your joy is so inspiring! Keep it up and enjoy every moment.",
    "I’m so glad to see you happy. May this joy stay with you!",
    "It’s great to hear that you're in a good place emotionally. Keep that joy alive!",
    "It sounds like life is treating you well! Enjoy that joy to the fullest.",
    "I’m thrilled that you're feeling joyful. What’s the source of your happiness?",
    "That’s amazing! Let that joy flow through you all day long.",
    "You’re glowing with happiness! Stay joyful and keep shining.",
    "I’m so glad you're feeling this good! It’s great to hear.",
    "Happiness looks so good on you! Keep that joy close to your heart.",
    "It’s amazing to hear you’re feeling so joyful. Keep those good vibes going!",
    "That’s wonderful! May this joy fill your heart all day long.",
    "It’s great to see you in such a happy mood! Keep spreading that joy.",
    "I’m glad to hear you’re smiling today! Stay joyful and keep living in the moment.",
    "Such positive energy! I’m so happy for you.",
    "This joy is beautiful! Embrace it and let it carry you through your day.",
    "I’m so glad to hear that you're feeling happy and content. Stay joyful!",
    "Your joy is contagious! I'm so happy you're feeling this way.",
    "You have such a joyful spirit! Keep it alive and well.",
    "I love hearing about your joy! What’s making you so happy?",
    "It’s so great to hear you're feeling this good! Keep enjoying that joy.",
    "You deserve all the happiness in the world. Let that joy flow freely.",
    "I’m so happy to hear you're feeling this positive and joyful!",
    "I can feel your happiness radiating! What’s been making you so joyful?",
    "Keep that joy close to your heart. It’s wonderful to hear you’re feeling this way!",
    "I’m so happy you're feeling joyful! What’s the best part of your day so far?",
    "I’m so glad you’re embracing your happiness! Keep feeling joyful.",
    "I’m so happy to see you in such a good mood! What’s bringing you this joy?",
    "You deserve all the joy you’re feeling right now. Keep living in the moment!",
    "It’s amazing to hear you’re feeling this way! May the joy continue!",
    "I’m so glad you're feeling joyful. Keep enjoying life’s little moments.",
    "It sounds like you’re in a great place! Let that joy fill you up.",
    "I’m so glad you're radiating such positivity. What’s the cause of all this joy?",
    "Your happiness is making my day! Keep embracing that joy.",
    "That’s so wonderful! I’m so happy you’re feeling this way.",
    "Your joy is like a burst of sunshine! Stay happy and keep shining.",
    "What a wonderful mood you’re in! Stay joyful and embrace every moment.",
    "I love how joyful you sound! Keep enjoying the good times.",
    "You’ve got such a positive energy about you! Enjoy that joy to the fullest.",
    "It’s so good to hear you're feeling this happy. Keep spreading that joy!",
    "Your joy is inspiring! Keep it going and enjoy every second.",
    "I can tell that you’re in a wonderful place emotionally. Stay joyful!",
    "I’m so glad you're feeling this happy! Embrace the joy and let it carry you.",
    "It’s amazing to hear you're in such a great mood! What’s making you smile?",
    "You deserve all the happiness you're feeling right now! Let it last.",
    "Your joy is so uplifting! Keep the positive vibes flowing.",
    "I’m so happy you're feeling joyful today! What’s the best part of your day?",
    "You’ve got such an amazing energy about you. Keep spreading that joy!",
    "I’m glad you're feeling this good! May your happiness continue.",
    "I love hearing how happy you are! Let that joy carry you through the day.",
    "You seem so happy! Embrace that joy and let it guide you.",
    "It’s wonderful to hear you’re feeling joyful. Keep enjoying the moment.",
    "Such great vibes! I’m happy you’re feeling this joyful.",
    "I’m so glad you're radiating happiness! Keep it going.",
    "That’s so fantastic! Enjoy every moment of your joy.",
    "It sounds like life is treating you well! Keep that joy flowing.",
    "You’re filled with such positive energy! Stay joyful and keep smiling.",
    "I’m so happy you’re feeling joyful! What’s been making you feel so good?",
    "It’s amazing to hear you're so happy! Keep soaking up that joy.",
    "I love hearing about your joy! Stay happy and keep spreading it.",
    "I’m so glad you’re feeling this positive. Keep embracing that joy.",
    "That’s incredible! Let that joy fuel your day.",
    "You sound so happy! Let that joy light up your world.",
    "I’m so happy to hear you're in a joyful mood! Stay positive and keep shining.",
    "You’ve got such a joyful spirit! Let that happiness fill your heart.",
    "It’s amazing to hear you're feeling this way! What’s bringing you all this joy?",
    "I’m so glad to hear you're feeling so positive and happy!",
    "You deserve to feel this joyful! Keep living in that happiness.",
    "I’m so happy to hear that you're filled with joy. Keep that energy going!",
    "It’s wonderful to hear you're in a joyful mood. Enjoy it to the fullest.",
    "I’m so glad you're experiencing this happiness! Keep it going.",
    "Joy suits you! I’m so happy you're feeling this way.",
    "You’re glowing with happiness! Let that joy carry you through the day.",
    "I’m so happy you're feeling joyful! Keep it going and spread that positivity."
],

    'sadness': [
    "I'm really sorry you're feeling sad. Want to talk about it?",
    "It’s okay to feel down sometimes. I’m here to listen if you want to share.",
    "I understand that you're feeling sad. How can I support you?",
    "I'm here for you. If you need to talk about what's making you feel sad, I'm listening.",
    "I'm so sorry you're feeling this way. Want to talk about what's going on?",
    "Sadness can be overwhelming, but it's okay to feel it. I'm here if you want to share.",
    "It's okay to feel sad. Let me know if there's anything I can do to help.",
    "I understand you're feeling down right now. Would you like to talk about it?",
    "I'm really sorry you're going through this. I’m here to help however I can.",
    "I know it’s hard, but you’re not alone. Let’s talk it through if you’re ready.",
    "Sadness can feel like a heavy weight. I’m here to listen and help you through it.",
    "I'm here for you if you want to talk. Sometimes it helps to express how you’re feeling.",
    "I know it can be tough. Let’s talk about what's on your mind, if you feel comfortable.",
    "It’s okay to be sad. I’m here to listen if you need someone to talk to.",
    "I’m really sorry you’re feeling this way. Do you want to talk about what’s going on?",
    "It’s hard to deal with sadness. I’m here to help you through it if you want to share.",
    "I know things might feel heavy right now. If you want to talk, I’m here for you.",
    "I’m sorry you're feeling sad. Would you like to share what’s been bothering you?",
    "It’s okay to feel sad. Sometimes talking about it helps. I’m here for you.",
    "I can sense that you’re feeling down. Want to talk about what's going on?",
    "I know you're going through a tough time. I’m here to listen if you want to share.",
    "I'm so sorry you're feeling like this. Do you want to tell me what’s on your mind?",
    "I’m here for you during this tough time. Let me know if you’d like to talk.",
    "Feeling sad is okay. You don’t have to carry it alone. I’m here to listen.",
    "It’s okay to feel sad sometimes. You can always talk to me if you need to.",
    "I understand that sadness can feel isolating, but I’m here to listen if you need to talk.",
    "I’m really sorry you’re feeling this way. Want to share what’s making you sad?",
    "It’s okay to express your sadness. I’m here if you want to talk about it.",
    "I’m so sorry you're going through this. If you want to talk, I’m here.",
    "Sadness can be overwhelming, but you're not alone. I’m here to listen.",
    "I understand you're feeling down. Would you like to share what's making you sad?",
    "I'm really sorry to hear you're feeling like this. I’m here to talk if you want to.",
    "I know it's tough, but you don’t have to go through this alone. Let’s talk if you're ready.",
    "It's okay to feel sad sometimes. I’m here for you if you want to talk about it.",
    "I understand how you’re feeling. I’m here to listen if you need me.",
    "I’m really sorry you're going through this. Sometimes talking can help. What’s making you sad?",
    "I know you're feeling down, but you don’t have to carry it alone. I’m here to listen.",
    "Sadness is a normal emotion, but it doesn’t mean you're alone. I’m here if you want to share.",
    "I’m sorry you're feeling like this. Do you want to talk about what’s causing the sadness?",
    "It’s okay to feel sad. I’m here for you if you want to talk about it.",
    "Sadness can feel heavy, but it will pass. I’m here for you while you process it.",
    "It’s okay to be sad. You don’t have to hold it in. I’m here to listen if you need to talk.",
    "I’m really sorry you're feeling this way. Want to talk about what’s on your mind?",
    "I know sadness can be tough to handle. I’m here to talk if you feel like sharing.",
    "It's okay to feel this way. Sometimes talking can help, and I’m here if you need to.",
    "I understand that you're feeling down right now. Do you want to share what’s bothering you?",
    "I know it can be hard. I'm here to listen if you want to talk about what’s making you sad.",
    "Sadness is a part of life, but it doesn’t last forever. I’m here to help however I can.",
    "I’m really sorry you’re feeling sad. Do you want to tell me more about it?",
    "Sometimes sadness can feel overwhelming. I’m here to listen if you want to talk.",
    "You’re not alone in this. I’m here to listen and help you through this sad moment.",
    "I’m sorry you’re feeling this way. It’s okay to talk about it if you’re ready.",
    "I understand sadness can be tough. If you need to talk, I’m here for you.",
    "I’m really sorry you’re going through this. Let’s talk about it if you feel like sharing.",
    "Sadness is a heavy emotion, but you don’t have to carry it by yourself. I’m here for you.",
    "I can hear the sadness in your words. I’m here if you want to share what’s on your mind.",
    "It’s okay to feel sad. I’m here for you if you want to talk it through.",
    "I know you're going through a rough time. I’m here to listen if you need to talk.",
    "I’m really sorry you're feeling sad. If you need someone to talk to, I’m here for you.",
    "I can sense your sadness. Want to talk about what’s causing it?",
    "It’s okay to feel this way. You don’t have to go through it alone. I’m here to listen.",
    "Sadness can feel isolating, but I’m here for you if you want to talk about it.",
    "I’m really sorry you’re feeling down. Want to share what's making you feel this way?",
    "It’s okay to be sad sometimes. I’m here to listen if you want to talk it out.",
    "I understand sadness can be tough. Let’s talk through what’s making you feel this way.",
    "I'm here for you during this difficult time. Want to talk about what's causing the sadness?",
    "It’s okay to be sad. I’m here to listen if you want to share how you're feeling.",
    "I'm so sorry you're feeling this way. Want to tell me what's going on?",
    "I understand you're feeling sad. Want to share what's on your mind?",
    "I’m here for you. If you want to talk about what’s making you sad, I’m listening.",
    "Sadness can be hard to handle, but you don’t have to go through it alone. I’m here for you.",
    "I’m really sorry you're feeling down. It’s okay to talk about it if you want.",
    "It’s okay to be sad. I’m here for you if you want to talk through it.",
    "I know it's tough right now. Want to talk about what's making you feel sad?",
    "Sadness can be draining, but it will get better. I’m here for you if you need to talk.",
    "I understand you're feeling down. It’s okay to feel that way. I’m here to listen if you want to talk.",
    "I’m really sorry you're feeling sad. Want to share what’s bothering you?",
    "Sometimes sadness is just part of life, but I’m here to help you through it.",
    "I know you’re going through a tough time. Want to talk about it?",
    "It’s okay to feel sad. I’m here for you if you want to share what's going on.",
    "Sadness can feel overwhelming, but I’m here to listen and help however I can.",
    "I understand you're feeling down. Let me know how I can help.",
    "I’m really sorry you're feeling this way. If you want to talk, I’m here for you.",
    "Sadness is something we all go through. You don’t have to face it alone. I’m here to listen.",
    "I'm sorry you're feeling sad. Want to talk about what's on your mind?",
    "It’s okay to feel sad. I’m here for you if you want to talk about it.",
    "I understand you're going through a tough time. Let me know if you want to talk.",
    "I know sadness can feel like a heavy burden. I’m here for you if you need to share.",
    "I’m really sorry you're feeling this way. What’s making you feel sad?"
],

    'surprise' : [
    "Wow, that’s unexpected! What happened?",
    "I didn’t see that coming! Tell me more.",
    "That’s quite a surprise! What’s going on?",
    "Oh wow, I didn’t expect that! What happened?",
    "I’m amazed! What’s the surprise?",
    "That’s definitely a surprise! What’s the story behind it?",
    "I wasn’t expecting that! What’s going on?",
    "I’m surprised! Tell me more about what happened.",
    "That’s incredible! How did that happen?",
    "Whoa, that’s a plot twist! What’s going on?",
    "I can’t believe it! What’s the big surprise?",
    "I didn’t see that coming! What’s the surprise?",
    "That’s amazing! I’d love to hear more about it.",
    "That’s definitely surprising! What led to this moment?",
    "I’m shocked! What’s the surprising news?",
    "What a surprise! What’s going on?",
    "I’m completely taken aback! What happened?",
    "That’s unexpected! I’d love to hear more about it.",
    "I didn’t expect that! What’s going on?",
    "Wow, that’s a twist! What happened?",
    "That’s a real surprise! Tell me more about it.",
    "What a shock! What’s the story behind this?",
    "I’m speechless! What’s going on?",
    "That’s unbelievable! What happened?",
    "I didn’t see that coming! How did that happen?",
    "I’m in shock! What’s going on?",
    "What a surprise! I didn’t see that happening!",
    "That’s a surprise! Tell me everything about it!",
    "Wow, I’m shocked! What’s the big surprise?",
    "I can’t believe it! What happened?",
    "I didn’t expect that! What’s the twist?",
    "That’s such a surprise! I need to hear more!",
    "That’s truly unexpected! What’s going on?",
    "I’m totally surprised! What’s the backstory?",
    "I didn’t think this would happen! What’s going on?",
    "That’s a real surprise! What’s the reason behind it?",
    "I’m really surprised! What’s the full story?",
    "What an unexpected turn of events! What happened?",
    "I can’t believe that! Tell me what happened!",
    "I didn’t expect that! I’m curious to know more.",
    "Whoa, that’s a twist! How did that happen?",
    "That’s amazing! How did this happen?",
    "I’m shocked! What’s the story here?",
    "I didn’t expect that! You’ve got my attention!",
    "I’m surprised! How did that come about?",
    "I didn’t see that coming! What’s going on?",
    "That’s incredible! How did you manage that?",
    "Wow, I didn’t expect that at all! Tell me more.",
    "I’m really surprised! How did this happen?",
    "That’s an interesting turn of events! What happened?",
    "I’m shocked! What’s the surprise?",
    "That’s a real shock! What’s going on?",
    "I didn’t expect that! What’s going on?",
    "What a twist! How did this happen?",
    "Wow, that’s an unexpected surprise! What’s the story?",
    "I didn’t think that would happen! What’s going on?",
    "I’m amazed! What’s the surprise?",
    "I can’t believe it! What happened?",
    "That’s a big surprise! Tell me everything!",
    "I’m completely surprised! What’s the reason behind this?",
    "That’s an incredible turn of events! What’s going on?",
    "I didn’t see that coming! What’s the surprise?",
    "That’s a plot twist! What’s happening?",
    "Wow, that’s a surprise! How did this happen?",
    "I didn’t expect that! What’s the full story?",
    "I’m in disbelief! What’s going on?",
    "What a twist! What’s the surprise?",
    "That’s amazing! How did that happen?",
    "I’m really surprised! What’s going on?",
    "That’s unbelievable! What happened?",
    "Wow, I didn’t expect that! Tell me more.",
    "That’s incredible! I can’t wait to hear more.",
    "I’m really surprised! What happened?",
    "What a shock! What’s the story?",
    "Wow, I didn’t see that coming! Tell me more!",
    "That’s a big surprise! What’s the backstory?",
    "I can’t believe it! What’s the story?",
    "That’s a huge surprise! What’s going on?",
    "I’m shocked! What’s the story behind this?",
    "I didn’t expect that at all! Tell me everything!",
    "I’m surprised! What’s the full story?",
    "That’s unbelievable! How did that happen?",
    "Wow, that’s a surprise! What happened?",
    "I can’t believe it! How did that happen?",
    "What a twist! I can’t wait to hear more.",
    "I didn’t expect that! What’s the full story?",
    "Wow, that’s shocking! What happened?",
    "That’s incredible! What’s the backstory?",
    "I’m amazed! How did that happen?",
    "Wow, I didn’t expect that! Tell me more.",
    "That’s a twist! What’s the surprise?",
    "I’m really shocked! What’s going on?",
    "What a surprise! How did that happen?",
    "That’s amazing! What’s the surprise?",
    "Wow, that’s unbelievable! What happened?",
    "That’s unexpected! What’s the story?",
    "I didn’t see that coming! Tell me what happened.",
    "What an unexpected turn! How did that happen?",
    "I’m shocked! How did that happen?",
    "That’s a real surprise! Tell me more about it.",
    "Wow, I didn’t expect that! What’s going on?",
    "I’m in shock! What’s the story?",
    "That’s unbelievable! What’s going on?",
    "Wow, I didn’t see that coming! What happened?"
],

    'disgust' : [
    "That sounds really unpleasant. What’s going on?",
    "I can sense your disgust. Want to talk about it?",
    "That doesn’t sound pleasant at all. Do you want to share?",
    "That’s awful! Want to talk about why it’s bothering you?",
    "I understand how you feel. That sounds really gross.",
    "That’s really disturbing. Do you want to discuss it?",
    "I can tell you're disgusted. Would you like to talk about it?",
    "That’s really unpleasant. I’m here if you want to talk.",
    "I understand that feeling of disgust. Want to vent about it?",
    "Ugh, that sounds disgusting! Want to tell me what happened?",
    "I can tell you're not happy about this. Want to talk it through?",
    "That’s really gross! What’s going on?",
    "Yikes, that doesn’t sound great! Want to talk about it?",
    "That’s pretty revolting. Do you want to share more?",
    "I can sense your disgust. How can I help?",
    "Ugh, that’s awful! Let me know if you want to talk about it.",
    "I can feel the disgust in your words. Want to talk about what happened?",
    "That sounds terrible! Want to vent about it?",
    "That’s really disturbing! Want to share what happened?",
    "I understand why you feel disgusted. How can I help?",
    "That’s really unpleasant. Want to talk it through?",
    "I get that you’re disgusted by this. Do you want to discuss it?",
    "I can hear how disgusted you are. Want to talk about it?",
    "Yikes, that’s not good! What’s bothering you?",
    "That’s really revolting. Want to talk about it?",
    "I understand how you feel. That’s really unpleasant.",
    "That’s pretty gross! Want to talk about it?",
    "I can sense your discomfort. Want to talk about what happened?",
    "That’s really off-putting! What’s going on?",
    "I understand that disgust. What happened?",
    "That sounds pretty awful. Do you want to discuss it?",
    "I can sense the disgust in your tone. Want to talk it through?",
    "That’s disgusting! Want to share what’s bothering you?",
    "I get it, that’s really unpleasant. Want to vent?",
    "I can understand your disgust. Want to talk about it?",
    "That’s a tough situation. How can I help you feel better?",
    "Yikes, that sounds really unpleasant. Want to talk about it?",
    "I can hear your disgust. What happened?",
    "I understand how you feel. That sounds really gross.",
    "That’s pretty revolting! What happened?",
    "I get it, that’s really disgusting. Want to share more?",
    "I can sense the disgust. Want to talk about it?",
    "That’s really off-putting! How can I help?",
    "Ugh, that sounds awful. Want to talk it through?",
    "That’s really unpleasant. Want to discuss it?",
    "I can hear your disgust. Want to share what’s going on?",
    "Yikes, that’s not pleasant at all. Want to talk about it?",
    "I understand that feeling. That sounds really gross.",
    "That’s pretty disturbing. Want to talk about it?",
    "I can tell you're disgusted. Want to share more?",
    "That sounds terrible! Want to talk about what happened?",
    "I can feel your disgust. How can I help?",
    "That’s really unsettling. Want to talk about it?",
    "I understand how you feel. That’s a tough situation.",
    "That’s pretty disturbing. Want to share what’s going on?",
    "Ugh, that sounds really unpleasant. What’s going on?",
    "I can sense the disgust. Want to talk it through?",
    "That’s really off-putting! Want to talk about it?",
    "I understand how you feel. That’s really gross.",
    "That’s pretty revolting. Want to share more?",
    "I can tell you’re disgusted. How can I help?",
    "I can feel your disgust. Want to talk about it?",
    "That’s disgusting! Want to tell me what happened?",
    "I understand how you feel. That’s really unpleasant.",
    "Yikes, that sounds really gross. Want to talk about it?",
    "I can tell you're disgusted. Want to vent about it?",
    "That’s awful! Want to share more about what’s bothering you?",
    "That’s really revolting. Want to talk about it?",
    "I get it, that’s really disgusting. Want to tell me more?",
    "I can sense the disgust. How can I help?",
    "That sounds terrible! Want to talk about what happened?",
    "I understand how you feel. That’s a tough situation.",
    "I can tell you're disgusted. Want to talk about it?",
    "Ugh, that sounds awful! Want to talk through it?",
    "I can sense your disgust. Want to share more?",
    "I understand how you feel. That sounds really gross.",
    "That’s really off-putting. Want to talk about it?",
    "I can hear the disgust. How can I help?",
    "That’s pretty revolting! Want to talk about what’s going on?",
    "I understand that feeling of disgust. Want to vent?",
    "That sounds terrible! What’s going on?",
    "That’s really gross! Want to talk about it?",
    "I get it, that’s really unpleasant. Want to talk about it?",
    "I can feel your disgust. How can I help?",
    "That’s pretty disgusting. What happened?",
    "That’s really unsettling. Want to talk it out?",
    "I can tell you're disgusted. Want to share what’s going on?",
    "That’s really disturbing! Want to talk about it?",
    "I understand how you feel. That’s a tough situation.",
    "That’s really unpleasant. Want to talk about it?",
    "That’s pretty revolting! Want to share more?",
    "I can hear your disgust. Want to share what’s going on?",
    "Yikes, that sounds awful. Want to talk through it?"
],

    'neutral':[
    "It seems like you're in a neutral mood. How can I help?",
    "You seem calm. What's on your mind?",
    "It looks like you're in a balanced mood today. What's going on?",
    "I sense a neutral vibe from you. Anything you'd like to share?",
    "You're in a neutral state. Anything you'd like to talk about?",
    "It seems like you're in the middle ground today. How's everything?",
    "You’re in a neutral mood. Feel free to share anything.",
    "It looks like things are stable. How’s everything going?",
    "You seem to be feeling neutral. Anything you'd like to discuss?",
    "You’re in a steady mood. Is there anything you'd like to talk about?",
    "You seem calm and collected today. What’s on your mind?",
    "It’s a balanced mood. Anything you’d like to chat about?",
    "You seem centered today. Want to share anything?",
    "It looks like everything is balanced. What’s on your mind?",
    "It seems like you're neither up nor down today. What's going on?",
    "You seem in a stable mood today. How are things going?",
    "You’re in a neutral zone. Anything you'd like to talk about?",
    "It looks like you're feeling calm today. What's happening?",
    "I sense a balanced mood. What's been going on?",
    "You seem content but neutral today. Anything you want to discuss?",
    "You’re feeling steady today. Let me know if you want to talk.",
    "You're not feeling extreme emotions today, huh? Want to talk?",
    "You’re in the middle, huh? Anything going on in your world?",
    "It seems like you're not too high or low today. How’s everything?",
    "You seem relaxed today. Anything you'd like to chat about?",
    "You’re in a neutral mood. Anything specific on your mind?",
    "You seem to be going through the day without strong emotions. How’s that?",
    "You seem grounded today. Anything I can help with?",
    "You seem to be in a neutral state of mind. Anything on your mind?",
    "You're keeping it cool today. How can I assist you?",
    "You seem at ease today. What’s going on in your world?",
    "It seems like you're in the middle ground today. What's on your mind?",
    "You're taking it easy today. Want to talk about anything?",
    "You seem balanced today. How’s everything going?",
    "I see you're in a calm mood today. How are things going?",
    "You're in a neutral space. Anything on your mind?",
    "You seem stable. Is everything going alright?",
    "I sense a neutral tone. How can I assist you today?",
    "It’s a steady mood today. What can I do for you?",
    "You seem to be at peace today. Want to chat?",
    "Everything seems calm and neutral. What can I do for you?",
    "You seem like you’re in a neutral frame of mind today. Anything I can do?",
    "You’re staying grounded. What’s on your mind?",
    "It’s a calm and steady mood today. What's going on?",
    "You seem content and stable. Anything I can do for you?",
    "You seem neutral today. Want to talk about how things are going?",
    "You’re in a good middle ground today. What’s happening?",
    "You’re staying even-keeled today. How can I assist?",
    "You’re in a neutral place. Anything I can help with?",
    "You seem to be in a quiet state of mind. How’s everything?",
    "You’re staying centered today. What's on your mind?",
    "You seem to be maintaining a steady mood. What's up?",
    "I sense a neutral vibe. How are things on your end?",
    "You’re feeling balanced. Anything you want to chat about?",
    "You seem unphased. How can I be of help today?",
    "You’re in a calm, neutral mood. Anything you want to share?",
    "You seem like you’re just chilling today. Want to talk?",
    "You’re holding steady today. Anything on your mind?",
    "You seem balanced and calm. Anything you’d like to chat about?",
    "You’re not feeling overly emotional today. How’s everything?",
    "You seem peaceful and neutral. What’s been going on?",
    "You’re taking it easy today. Want to talk through anything?",
    "I sense a calm and neutral energy. Anything I can help with?",
    "You’re in a neutral space today. How can I assist?",
    "You seem level-headed today. Anything you need?",
    "You’re not feeling too high or low. What's been happening?",
    "You seem collected today. How’s everything?",
    "You’re in a steady mood. What’s going on?",
    "You seem in a calm and neutral space today. How can I help?",
    "You’re keeping things calm. Anything on your mind?",
    "You seem in a steady frame of mind. How are things with you?",
    "You're in a neutral place. Anything you'd like to talk about?",
    "You seem steady and calm. What's on your mind?",
    "You're feeling balanced today. How can I help?",
    "You seem to be in a grounded place today. Anything you’d like to share?",
    "You seem to be going with the flow. Want to talk?",
    "You're in a neutral mood. How’s everything on your end?",
    "You seem like you're just getting through the day. Anything I can help with?",
    "It seems like you're in the middle ground. What's going on?",
    "You’re staying level today. Anything you'd like to talk about?",
    "You’re in a neutral mood today. How’s everything?",
    "You seem calm and collected today. What’s been going on?",
    "You’re not feeling extreme emotions today. How’s that going?",
    "You’re staying neutral today. Anything I can help with?",
    "You’re maintaining a calm demeanor. Want to talk about anything?",
    "You seem to be in a balanced place today. What’s going on?",
    "You seem to be feeling calm. Anything I can do for you?",
    "You're in a steady mood. What’s on your mind?",
    "You’re in the middle today. How’s everything?",
    "You seem neutral today. Want to talk about anything?",
    "You seem calm and composed. What’s been happening?",
    "You’re in a neutral state. Anything I can do for you?",
    "You’re feeling steady today. Want to chat?",
    "You seem neutral today. How can I help?",
    "You seem unbothered today. What's going on?",
    "You seem centered. How’s everything on your end?",
    "You seem balanced today. Want to talk about it?",
    "You’re feeling steady today. Want to share anything?",
    "You seem to be doing fine today. Anything you'd like to discuss?",
    "You seem calm. Want to talk about how things are going?",
    "You’re in a stable mood today. Want to share anything?",
    "You’re in a neutral zone today. What's on your mind?",
    "You seem neutral today. What’s happening?"
],

}
 #Ensure you have downloaded the necessary NLTK data


nltk.download('punkt')
nltk.download('stopwords')

# Function to preprocess text: Tokenize, remove stopwords, and stem
def preprocess_text(text):
    stop_words = set(stopwords.words('english'))
    tokens = word_tokenize(text.lower())  # Tokenize and convert to lowercase
    filtered_tokens = [word for word in tokens if word.isalnum() and word not in stop_words]
    return " ".join(filtered_tokens)

# Function to get emotion from sentiment score
def get_emotion_from_sentiment(sentiment_score):
    if sentiment_score >= 0.7:
        return 'joy'
    elif 0.5 <= sentiment_score < 0.7:
        return 'neutral'
    elif sentiment_score <= -0.7:
        return 'anger'
    elif -0.5 <= sentiment_score < -0.7:
        return 'fear'  # Assuming very negative values represent fear
    elif -0.3 <= sentiment_score < -0.5:
        return 'sadness'
    elif 0.3 <= sentiment_score < 0.5:
        return 'surprise'  # Assuming positive but lower score represents surprise
    elif -0.3 < sentiment_score < 0:
        return 'disgust'  # Assuming mild negative emotions represent disgust
    else:
        return 'neutral'

# Function to find the best response based on the similarity between the user message and the emotion responses
def get_emotion_response(emotion, user_message):
    if emotion not in emotion_responses:
        return "I'm not sure how to respond to that emotion."

    # Preprocess the user message
    user_message_processed = preprocess_text(user_message)
    
    # Prepare the responses for the current emotion
    responses = emotion_responses[emotion]
    
    # Preprocess the responses
    processed_responses = [preprocess_text(response) for response in responses]

    # Use TF-IDF vectorizer to convert text into vector form
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform([user_message_processed] + processed_responses)

    # Calculate cosine similarity between user message and all responses
    cosine_similarities = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:]).flatten()
    
    # Get the index of the most similar response
    most_similar_index = cosine_similarities.argmax()

    # Return the best response based on the highest similarity score
    return responses[most_similar_index]

# Views
def index(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        request.session['username'] = username  # Store the username in the session
        return redirect('chatbot')
    return render(request, 'index.html')

def chatbot(request):
    # Check if username is stored in the session
    username= request.session.get('username')
    if not username:
        return redirect('index')  # If no username, redirect to index view

    return render(request, 'chatbot.html', {'username': username})  # Pass the username to the template

def save_chat_log(username, chat_log):
    # Create or open the document to save chat logs
    document = Document()
    file_name = f"chat_logs/{username}_chat_log.docx"

    # Check if the directory exists
    if not os.path.exists('chat_logs'):
        os.makedirs('chat_logs')

    # Add message and response to the document
    document.add_paragraph(f"Chat with {username} - {timezone.now()}\n")
    for message, response in chat_log:
        document.add_paragraph(f"You: {message}")
        document.add_paragraph(f"Bot: {response}")
    
    # Save the document
    document.save(file_name)

def send_message(request):
    if request.method == 'POST':
        user_message = request.POST.get('message')
        
        # Retrieve the username from the session
        username = request.session.get('username')

        if user_message.lower() == 'quit':
            chat_log = []
            save_chat_log(username, chat_log)
            return JsonResponse({'status': 'chat ended'})
        
        # Get the sentiment score using VADER
        sentiment = sia.polarity_scores(user_message)
        sentiment_score = sentiment['compound']
        
        # Get the emotion based on sentiment score
        emotion = get_emotion_from_sentiment(sentiment_score)

        # Get the bot's response based on emotion
        bot_response = get_emotion_response(emotion, user_message)

        # Save the conversation to the database
        chat_log = ChatLog(username=username, user_message=user_message, bot_response=bot_response)
        chat_log.save()

        # Save chat log to document (optional)
        save_chat_log(username, [(user_message, bot_response)])

        return JsonResponse({'response': bot_response})